name: Sync labels across all existing repos

on:
  workflow_dispatch: # manually triggered

permissions:
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run label sync on each repo
        run: |
          chmod +x sync.sh
          ./sync.sh
